# Generated by Django 4.1.3 on 2022-12-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mainapp/', verbose_name='Выберите фотографию: ')),
            ],
            options={
                'verbose_name': 'Предложка для главной страницы',
                'verbose_name_plural': 'Предложка для главной страницы',
            },
        ),
    ]
