# Generated by Django 4.1.3 on 2022-12-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mainapp/', verbose_name='Выберите фотографию: ')),
                ('name', models.CharField(max_length=50, verbose_name='Название: ')),
                ('description', models.CharField(max_length=50, verbose_name='Описание в админке: ')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL перехода: ')),
            ],
            options={
                'verbose_name': 'Оформление страниц',
                'verbose_name_plural': 'Оформление страниц',
            },
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
