# Generated by Django 4.1.3 on 2023-04-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_mainpage_delete_suggestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Оформление главной страницы страниц', 'verbose_name_plural': 'Оформление главной страницы страниц'},
        ),
    ]
