# Generated by Django 4.0.1 on 2022-01-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название:')),
                ('person_info', models.CharField(max_length=100, verbose_name='ФИО:')),
                ('person_email', models.EmailField(max_length=50, verbose_name='Введите свой Email:')),
                ('full_text', models.TextField(verbose_name='Что выставляете на продажу:')),
                ('date', models.DateTimeField(verbose_name='Дата публикации:')),
            ],
            options={
                'verbose_name': 'Торговое предложение',
                'verbose_name_plural': 'Торговые предложения',
            },
        ),
    ]
