# Generated by Django 4.0.1 on 2022-09-05 21:50

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mainapp/', verbose_name='Выберите фотографию логотипа: ')),
                ('photo_background', models.ImageField(blank=True, null=True, upload_to='mainapp/', verbose_name='Выберите фотографию на задний план: ')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=1050, verbose_name='Описание: ')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('output_main', models.BooleanField(default=False, verbose_name='Добавить на главную')),
            ],
            options={
                'verbose_name': 'Список Брендов Для Вещей',
                'verbose_name_plural': 'Список Брендов Для Вещей',
            },
        ),
        migrations.CreateModel(
            name='BrandAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mainapp/', verbose_name='Выберите фотографию: ')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Описание: ')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Список Брендов Для Аксессуаров',
                'verbose_name_plural': 'Список Брендов Для Аксессуаров',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая цена')),
                ('in_order', models.BooleanField(default=False)),
                ('session_key', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ключ сессии')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория Для Вещей',
                'verbose_name_plural': 'Категории Для Вещей',
            },
        ),
        migrations.CreateModel(
            name='CategoryAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория Для Аксессуаров',
                'verbose_name_plural': 'Категория Для Аксессуаров',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('session_key', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ключ сессии')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mainapp/', verbose_name='Выберите фотографию: ')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=9, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер',
                'verbose_name_plural': 'Размеры',
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mainapp/', verbose_name='Выберите фотографию: ')),
            ],
            options={
                'verbose_name': 'Предложка для главной страницы',
                'verbose_name_plural': 'Предложка для главной страницы',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('for_anonymous_user', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='ProductAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='mainapp/', verbose_name='Выберите фотографию: ')),
                ('photo_product1', models.ImageField(blank=True, null=True, upload_to='mainapp/', verbose_name='Выберите фотографию: ')),
                ('photo_product2', models.ImageField(blank=True, null=True, upload_to='mainapp/', verbose_name='Выберите фотографию: ')),
                ('photo_product3', models.ImageField(blank=True, null=True, upload_to='mainapp/', verbose_name='Выберите фотографию: ')),
                ('title', models.CharField(max_length=32, verbose_name='Название: ')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание: ')),
                ('stock', models.IntegerField(default=1, verbose_name='Наличие на складе')),
                ('discount', models.BooleanField(default=True, verbose_name='Товар со скидкой')),
                ('price', models.IntegerField(verbose_name='Введите цену: ')),
                ('sale_price', models.IntegerField(blank=True, null=True, verbose_name='Введите цену со скидкой')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.brandaccessories', verbose_name='Бренд аксессуара>')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.categoryaccessories', verbose_name='Категория аксесуара')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sex')),
                ('size', models.ManyToManyField(blank=True, null=True, to='mainapp.Size', verbose_name='Размеры')),
            ],
            options={
                'verbose_name': 'Каталог Аксессуаров',
                'verbose_name_plural': 'Каталог Аксессуаров',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='mainapp/', verbose_name='Выберите фотографию: ')),
                ('photo_product1', models.ImageField(blank=True, null=True, upload_to='mainapp/', verbose_name='Выберите фотографию: ')),
                ('photo_product2', models.ImageField(blank=True, null=True, upload_to='mainapp/', verbose_name='Выберите фотографию: ')),
                ('photo_product3', models.ImageField(blank=True, null=True, upload_to='mainapp/', verbose_name='Выберите фотографию: ')),
                ('title', models.CharField(max_length=32, verbose_name='Название: ')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание: ')),
                ('stock', models.IntegerField(default=1, verbose_name='Наличие на складе')),
                ('discount', models.BooleanField(default=True, verbose_name='Товар со скидкой')),
                ('new_product', models.BooleanField(default=True, verbose_name='Добавить в новинки')),
                ('price', models.IntegerField(verbose_name='Введите цену: ')),
                ('sale_price', models.IntegerField(blank=True, null=True, verbose_name='Введите цену со скидкой')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.sex')),
                ('size', models.ManyToManyField(blank=True, null=True, to='mainapp.Size', verbose_name='Размеры')),
            ],
            options={
                'verbose_name': 'Каталог Вещей',
                'verbose_name_plural': 'Каталог Вещей',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=1024, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('new', 'Не подтвержден'), ('in_progress', 'Подтвержден'), ('is_ready', 'Готов к выдаче'), ('completed', 'Получен покупателем')], default='new', max_length=100, verbose_name='Статус заказа')),
                ('buying_type', models.CharField(choices=[('self', 'Самовывоз'), ('delivery', 'Доставка')], max_length=100, verbose_name='Способ получения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментарий к заказу')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Дата создания заказа')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата получения заказа')),
                ('session_key', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ключ сессии')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart', verbose_name='Корзина')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mainapp.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_product', models.BooleanField(default=True, verbose_name='Добавить в новинки')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_product', to='mainapp.product', verbose_name='Вещи из продуктов')),
                ('product_accessories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.productaccessories', verbose_name='Вещи из аксессуаров')),
            ],
            options={
                'verbose_name': 'Новинки',
                'verbose_name_plural': 'Новинки',
            },
        ),
        migrations.CreateModel(
            name='DiscountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.BooleanField(default=True, verbose_name='Добавить в скидки')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='back_product_discount', to='mainapp.product', verbose_name='Вещи из продуктов')),
                ('product_accessories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.productaccessories', verbose_name='Вещи из аксессуаров')),
            ],
            options={
                'verbose_name': 'Скидки',
                'verbose_name_plural': 'Скидки',
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('size', models.CharField(blank=True, max_length=9, null=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Общая цена')),
                ('session_key', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Ключ сессии')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='mainapp.cart', verbose_name='Корзина')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Корзина с продуктами',
                'verbose_name_plural': 'Корзина с продуктами',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Владелец'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='mainapp.CartProduct'),
        ),
    ]
