# Generated by Django 4.0.1 on 2022-09-05 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session_key',
        ),
    ]
