# Generated by Django 4.1.3 on 2023-04-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='accessories_size',
            field=models.BooleanField(default=False, verbose_name='Для аксессуаров'),
        ),
        migrations.AddField(
            model_name='size',
            name='clothing_size',
            field=models.BooleanField(default=False, verbose_name='Для одежды'),
        ),
        migrations.AddField(
            model_name='size',
            name='shoe_size',
            field=models.BooleanField(default=False, verbose_name='Для обуви'),
        ),
    ]
