# Generated by Django 4.1.3 on 2023-04-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_size_accessories_size_size_clothing_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='accessories_size',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Для аксессуаров'),
        ),
        migrations.AlterField(
            model_name='size',
            name='clothing_size',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Для одежды'),
        ),
        migrations.AlterField(
            model_name='size',
            name='shoe_size',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Для обуви'),
        ),
    ]
