# Generated by Django 4.1.3 on 2023-04-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_size_accessories_size_alter_size_clothing_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
